FROM ubuntu:22.04
RUN mkdir -p /opt/medcab \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends build-essential zlib1g-dev libpq-dev libicu-dev \
	&& apt-get install -y ca-certificates && update-ca-certificates \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

ARG YESOD_SUPERUSER_USERNAME
ARG YESOD_SUPERUSER_PASSWORD
ARG YESOD_DEMO_LANG=EN
ARG YESOD_GOOGLE_SITE_VERIFICATION
ARG YESOD_GOOGLE_CLIENT_ID
ARG YESOD_GOOGLE_CLIENT_SECRET
ARG YESOD_MS_VALIDATE
ARG YESOD_RTC_PEER_CONNECTION_CONFIG

WORKDIR /opt/medcab
COPY medcab /opt/medcab
COPY static /opt/medcab/static
COPY config /opt/medcab/config

ENV YESOD_PORT=8080
ENV YESOD_DEMO_LANG=${YESOD_DEMO_LANG}
ENV YESOD_SUPERUSER_USERNAME=${YESOD_SUPERUSER_USERNAME}
ENV YESOD_SUPERUSER_PASSWORD=${YESOD_SUPERUSER_PASSWORD}
ENV YESOD_GOOGLE_SITE_VERIFICATION=${YESOD_GOOGLE_SITE_VERIFICATION}
ENV YESOD_GOOGLE_CLIENT_ID=${YESOD_GOOGLE_CLIENT_ID}
ENV YESOD_GOOGLE_CLIENT_SECRET=${YESOD_GOOGLE_CLIENT_SECRET}
ENV YESOD_MS_VALIDATE=${YESOD_MS_VALIDATE}
ENV YESOD_RTC_PEER_CONNECTION_CONFIG=${YESOD_RTC_PEER_CONNECTION_CONFIG}

EXPOSE 8080
CMD ["./medcab"]
