InvalidUrlOrRemoved: Invalid URL or resource removed
PageNotFound: Page not found
Resources: Resources
SourceCode: Source code
Documentation: Documentation
Doctors: Doctors
Data: Data
NotIndicated: Not indicated
Birthday: Birthday
Other: Other
Male: Male
Female: Female
Gender: Gender
Edit: Edit
PersonalInfo: Personal info
Account: Account
Home: Home
HomePage: Home page
PermissionDenied: Permission denied
DidNotGetEmail: Didn't receive the email?
CreatePassword: Create password
EmailVerification: Email verification
Verification: Verification
Registration: Registration
ResendEmail: Resend email
LoginRequired: You must login to access this page
AnotherAccountAccessProhibited: Access to another user's account is prohibited
OtherProfileChangeRestricted: Changing another user's profile is restricted
GmailAccountNotSet: Gmail account is not set. Initialize tokens.
Authentication: Authentication
PasswordRecovery: Password recovery
ForgotPassword: Forgot password
ForgotYourPassword: Forgot your password?
DoNotHaveAnAccount: Don't have an account?
CreateAccount: Create account
GmailAccount: Gmail account
ClickToVerifyAccount: Click the link in the email to verify your account
JustSentEmailTo: We just sent an email to
VerifyEmailPlease: Please verify your email
SignInViaEmail: Sign in via email
Cleared: Cleared
InvalidFormData: Invalid form data
RecordDeleted: Record deleted
ClearSettings: Clear
RecordEdited: Record edited
InvalidStoreType: Invalid store type
StoreType: Store type
Database: Database
UserSession: User session
GoogleSecretManager: Google Secret Manager
Initialize: Initialize
Tokens: Tokens
UserRegistered: User registered
FullName: Full name
Save: Save
Cancel: Cancel
UserAccount: User account
Photo: Photo
Password: Password
EmailAddress: Email address
Or: or
Back: Back
SignInWithGoogle: Sign in with Google
VideoConference: Video conference
SignOut: Sign out
SignIn: Sign in
SignUp: Sign up
Login: Login
MainMenu: Main menu
Welcome: Welcome
AppDescription: Medical Cabinet 
AppName: MedCab