GmailAccount: Gmail account
ClickToVerifyAccount: Click the link in the email to verify your account
JustSentEmailTo: We just sent an email to
VerifyEmailPlease: Please verify your email
SignInViaEmail: Sign in via email
Cleared: Cleared
InvalidFormData: Invalid form data
RecordDeleted: Record deleted
ClearSettings: Clear
RecordEdited: Record edited
InvalidStoreType: Invalid store type
StoreType: Store type
Database: Database
UserSession: User session
Initialize: Initialize
Tokens: Tokens
UserRegistered: User registered
FullName: Full name
Save: Save
Cancel: Cancel
UserAccount: User account
Photo: Photo
Password: Password
EmailAddress: Email address
Or: or
Back: Back
SignInWithGoogle: Sign in with Google
VideoConference: Video conference
SignOut: Sign out
SignIn: Sign in
SignUp: Sign up
Login: Login
MainMenu: Main menu
Welcome: Welcome
AppDescription: Medical Cabinet 
AppName: MedCab