AcceptNotifyMeForAudio name: Avertir lorsque #{name} passe un appel audio
AcceptNotifyMeForVideo name: Avertir lorsque #{name} passe un appel vidéo
AcceptNotifyMeForChat name: Avertir lorsque #{name} souhaite discuter
Notifications: Notifications
Configuration: Configuration
ChatParticipantsNotDefined: Les participants au chat ne sont pas définis
Message: Message
AccessDeniedPatiensOnly: Seuls les patients ont accès à cette page. Veuillez vous connecter en tant que patient
NoPatientsYet: Vous n'avez pas encore de patients
AccessDeniedDoctorsOnly: Seuls les médecins ont accès à cette page. Veuillez vous connecter en tant que médecin
Patient: Patient
Patients: Patients
Chat: Chat
Phone: Téléphone
InvalidRangeBoundaries: Limites de plage non valides
UpperBound: Limite supérieure
LowerBound: Limite inférieure
NormalValue: Valeur normale
NormalValues: Valeurs normales
RecordVitalSigns: Enregistrer les signes vitaux
BookAppointment: Prendre rendez-vous
AudioCall: Appel audio
VideoCall: Appel vidéo
FindDoctor: Trouver un médecin
Measurements: Mesures
Measurement: Mesure
Icon: Icône
Remarks: Remarques
Value: Valeur
Time: Heure
Date: Date
Record: Enregistrement
Records: Enregistrements
ElectronicHealthRecord: Dossier de santé électronique
Quantity: Grandeur
Quantities: Grandeurs
Categories: Catégories
Configure: Configurer
Settings: Paramètres
Manage: Gérer
Subtags: Sous-étiquettes
Subtag: Sous-étiquette
Tags: Étiquettes
Tag: Étiquette
Group: Groupe
MedicalSign: Signe médical
MedicalSigns: Signes médicaux
UnitOfMeasure: Unité de mesure
Symbol: Symbole
MeasurementUnit: Unité de mesure
NoDataYet: Il n'y a pas encore de données
UnitsOfMeasure: Unités de mesure
MeasurementUnits: Unités de mesure
IssueTracking: Signalement de bogues
Remove: Retirer
SinceDate: Depuis le
SearchEngineOptimization: Optimisation du moteur de recherche
AlreadyExists: Existe déjà
BasicEntities: Entités de base
CertificateDate: Date du certificat
Specializations: Spécialisations
JobTitle: Titre d'emploi
SpecialtyTitle: Titre
BackToHomepage: Retournez à la page d'accueil
DemoUserAccounts: Comptes d'utilisateurs démo
ThankYou: Merci
ConfirmEmailPlease: Veuillez confirmer votre adresse email en cliquant sur le lien ci-dessous
VerifyYourEmailAddress: Vérifiez votre adresse e-mail
AccessDeniedAdminsOnly: Seuls les administrateurs ont accès à cette page. Veuillez vous connecter avec un compte administrateur
ClientSecret: Secret client
ClientId: Identifiant client
Attribution: Attribution
None: Aucune
SuperuserCannotBeDeleted: Le superutilisateur ne peut pas être supprimé
Administrator: Administrateur
Username: Nom d'utilisateur
Superuser: Superutilisateur
NotSpecified: Not specified
No: Non
Yes: Oui
Email: E-mail
Google: Google
Verified: Vérifié
VerificationKey: Clé de vérification
User: Utilisateur
NoUsersYet: Il n'y a pas encore d'utilisateurs
Add: Ajouter
Users: Utilisateurs
Subspecialty: Surspécialité
NoSubspecialtiesYet: Il n'y a pas encore de sous-spécialités
Details: Détails
Subspecialties: Sous-spécialités
Tabs: Onglets
ConfirmPlease: Veuillez confirmer
RemoveAreYouSure: Êtes-vous sûr de vouloir supprimer ?
DeleteAreYouSure: Etes-vous sûr que vous voulez supprimer ?
ErDiagram: Diagramme ER
Name: Nom
Code: Code
Description: Description
NoSpecialtiesYet: Il n'y a pas encore de spécialités
Specialties: Spécialités
Specialty: Spécialité
Dele: Supprimer
RecordCreated: Enregistrement créé
Doctor: Médecin
Specialization: Spécialisation
Mobile: Mobile
NoDoctorsYet: Il n'y a pas encore de médecins
InvalidUrlOrRemoved: URL invalide ou ressource supprimée
PageNotFound: Page non trouvée
Resources: Ressources
SourceCode: Code source
AppDocumentation: Documentation de l'application
Documentation: Documentation
Doctors: Médecins
Data: Donnés
NotIndicated: Non indiqué
Birthday: Date de naissance
Other: Autre
Male: Masculin
Female: Féminin
Gender: Genre
Edit: Modifier
PersonalInfo: Données personnelles
Account: Compte
Home: Page d'accueil
HomePage: Page d'accueil
PermissionDenied: Permission refusée
DidNotGetEmail: Vous n'avez pas reçu l'e-mail ?
CreatePassword: Créer un mot de passe
EmailVerification: Vérification de l'E-mail
Verification: Vérification
Registration: Enregistrement
ResendEmail: Ré-envoyer l'email
LoginPlease: Veuillez vous connecter pour accéder à cette page
LoginRequired: Vous devez vous connecter pour accéder à cette page
AnotherAccountAccessProhibited: L'accès au compte d'un autre utilisateur est interdit
OtherProfileChangeRestricted: La modification du profil d'un autre utilisateur est restreinte
GmailAccountNotSet: Le compte Gmail n'est pas défini. Initialisez les jetons.
Authentication: Authentification
PasswordRecovery: Récupération de mot de passe
ForgotPassword: Forgot password
ForgotYourPassword: Mot de passe oublié?
DoNotHaveAnAccount: Vous n'avez pas de compte ?
CreateAccount: Créer un compte
GmailAccount: Compte Gmail
ClickToVerifyAccount: Cliquez sur le lien dans l'e-mail pour vérifier votre compte
JustSentEmailTo: Nous venons d'envoyer un email à
VerifyEmailPlease: Veuillez vérifier votre email
SignInViaEmail: Connectez-vous par e-mail
Cleared: Effacé
InvalidFormData: Données de formulaire incorrectes
RecordDeleted: L'enregistrement a été supprimé
ClearSettings: Effacer
RecordEdited: L'enregistrement a été modifié
InvalidStoreType: Type de stockage invalide
StoreType: Type de stockage
Database: Base de données
UserSession: Session utilisateur
GoogleSecretManager: Google Secret Manager
Initialize: Initialiser
Tokens: Jetons
UserRegistered: Utilisateur enregistré
FullName: Nom et prénom
Save: Enregistrer
Cancel: Annuler
UserAccount: Compte d'utilisateur
Photo: Photo
Password: Mot de passe
EmailAddress: Adresse e-mail
Or: ou
Back: Retour
SignInWithGoogle: Connectez-vous avec Google
VideoConference: Conférence vidéo
SignOut: Se déconnecter
SignIn: Se connecter
SignUp: S'inscrire
Login: Connexion
MainMenu: Menu principal
Welcome: Bienvenu
AppDescription: Application Web progressive pour les soins de santé
AppName: MedCab
MetaKeywords: soins de santé, progressif, web, application, pwa
MetaDescription: Application Web progressive pour les soins de santé

Doc001: Intégration avec des API externes

Doc002: Un compte superutilisateur est défini au moment du déploiement. Le superutilisateur gère les autres utilisateurs et accorde ou révoque les privilèges d'administrateur à des utilisateurs spécifiques.

Doc003 href: <a href=#{href} target=_blank>Le référentiel du projet</a> sur GitHub.

Doc004 href: Veuillez noter que l'application actuellement en cours d'exécution est une application de démonstration. Toutes les actions sont autorisées et encouragées. <a href=#{href} target=_blank>Signalez les bugs</a> sur GitHub.

Doc005 href: Un nouvel utilisateur peut s'inscrire en utilisant un compte Google ou en créant un nouveau compte sur la <a href=#{href}>page d'authentification</a>.

Doc006: Pour créer un nouveau compte, il est nécessaire de fournir une adresse email. L'adresse e-mail sera utilisée pour vérifier le compte et pour définir ou récupérer le mot de passe.

Doc007: Un superutilisateur (voir ci-dessous) peut accorder des privilèges d'administrateur à tout utilisateur enregistré. Un utilisateur doté du rôle d'administrateur peut à son tour accorder ou révoquer le rôle d'administrateur à d'autres utilisateurs enregistrés. Des privilèges d'administrateur sont requis pour gérer les données à l'échelle du système.

Doc008 href: Une unité de mesure est définie en fournissant un nom, un symbole et une description dans la section <a href=#{href}>« Unités de mesure »</a>.

Doc009: Chat entre médecins et patients

Doc010: Appel vidéo patient/médecin