None: Aucune
SuperuserCannotBeDeleted: Le superutilisateur ne peut pas être supprimé
Administrator: Administrateur
Username: Nom d'utilisateur
Superuser: Superutilisateur
NotSpecified: Not specified
No: Non
Yes: Oui
Email: E-mail
Google: Google
Verified: Vérifié
VerificationKey: Clé de vérification
User: Utilisateur
NoUsersYet: Il n'y a pas encore d'utilisateurs
Add: Ajouter
Users: Utilisateurs
Subspecialty: Surspécialité
NoSubspecialtiesYet: Il n'y a pas encore de sous-spécialités
Details: Détails
Subspecialties: Sous-spécialités
Tabs: Onglets
ConfirmPlease: Veuillez confirmer
DeleteAreYouSure: Etes-vous sûr que vous voulez supprimer?
ErDiagram: Diagramme ER
Name: Nom
Code: Code
Description: Description
NoSpecialtiesYet: Il n'y a pas encore de spécialités
Specialties: Spécialités
Specialty: Spécialité
Dele: Supprimer
RecordCreated: Enregistrement créé
Doctor: Médecin
Specialization: Spécialisation
Mobile: Mobile
NoDoctorsYet: Il n'y a pas encore de médecins
InvalidUrlOrRemoved: URL invalide ou ressource supprimée
PageNotFound: Page non trouvée
Resources: Ressources
SourceCode: Code source
Documentation: Documentation
Doctors: Médecins
Data: Donnés
NotIndicated: Non indiqué
Birthday: Date de naissance
Other: Autre
Male: Masculin
Female: Féminin
Gender: Genre
Edit: Modifier
PersonalInfo: Données personnelles
Account: Compte
Home: Page d'accueil
HomePage: Page d'accueil
PermissionDenied: Permission refusée
DidNotGetEmail: Vous n'avez pas reçu l'e-mail ?
CreatePassword: Créer un mot de passe
EmailVerification: Vérification de l'E-mail
Verification: Vérification
Registration: Enregistrement
ResendEmail: Ré-envoyer l'email
LoginRequired: Vous devez vous connecter pour accéder à cette page
AnotherAccountAccessProhibited: L'accès au compte d'un autre utilisateur est interdit
OtherProfileChangeRestricted: La modification du profil d'un autre utilisateur est restreinte
GmailAccountNotSet: Le compte Gmail n'est pas défini. Initialisez les jetons.
Authentication: Authentification
PasswordRecovery: Récupération de mot de passe
ForgotPassword: Forgot password
ForgotYourPassword: Mot de passe oublié?
DoNotHaveAnAccount: Vous n'avez pas de compte ?
CreateAccount: Créer un compte
GmailAccount: Compte Gmail
ClickToVerifyAccount: Cliquez sur le lien dans l'e-mail pour vérifier votre compte
JustSentEmailTo: Nous venons d'envoyer un email à
VerifyEmailPlease: Veuillez vérifier votre email
SignInViaEmail: Connectez-vous par e-mail
Cleared: Effacé
InvalidFormData: Données de formulaire incorrectes
RecordDeleted: L'enregistrement a été supprimé
ClearSettings: Effacer
RecordEdited: L'enregistrement a été modifié
InvalidStoreType: Type de stockage invalide
StoreType: Type de stockage
Database: Base de données
UserSession: Session utilisateur
GoogleSecretManager: Google Secret Manager
Initialize: Initialiser
Tokens: Jetons
UserRegistered: Utilisateur enregistré
FullName: Nom et prénom
Save: Enregistrer
Cancel: Annuler
UserAccount: Compte d'utilisateur
Photo: Photo
Password: Mot de passe
EmailAddress: Adresse e-mail
Or: ou
Back: Retour
SignInWithGoogle: Connectez-vous avec Google
VideoConference: Conférence vidéo
SignOut: Se déconnecter
SignIn: Se connecter
SignUp: S'inscrire
Login: Connexion
MainMenu: Menu principal
Welcome: Bienvenu
AppDescription: Cabinet Médical
AppName: MedCab

Doc001: Intégration avec des API externes