Attribution: Atribuire
None: Niciuna
SuperuserCannotBeDeleted: Superutilizatorul nu poate fi șters
Administrator: Administrator
Username: Nume de utilizator
Superuser: Superutilizator
NotSpecified: Non précisé
No: Nu
Yes: Da
Email: E-mail
Google: Google
Verified: Verificat
VerificationKey: Cheia de verificare
User: Utilizator
NoUsersYet: Nu există încă utilizatori
Add: Adaugă
Users: Utilizatori
Subspecialty: Subspecialitatea
NoSubspecialtiesYet: Nu există încă subspecialități
Details: Detalii
Subspecialties: Subspecialități
Tabs: File
ConfirmPlease: Vă rugăm să confirmați
DeleteAreYouSure: Sigur doriți să ștergeți?
ErDiagram: Diagrama ER
Name: Nume
Code: Cod
Description: Descriere
NoSpecialtiesYet: Nu există încă specialități
Specialties: Specialități
Specialty: Specialitatea
Dele: Șterge
RecordCreated: Înregistrarea creată
Doctor: Doctor
Specialization: Specializare
Mobile: Mobil
NoDoctorsYet: Nu există doctori încă
InvalidUrlOrRemoved: Adresă URL nevalidă sau resursă eliminată
PageNotFound: Pagina nu a fost găsită
Resources: Resurse
SourceCode: Codul sursă
Documentation: Documentație
Doctors: Doctori
Data: Date
NotIndicated: Nu este indicat
Birthday: Ziua de naștere
Other: Altul
Male: Masculin
Female: Feminin
Gender: Gen
Edit: Editează
PersonalInfo: Date personale
Account: Contul
Home: Pagina de start
HomePage: Pagina principală
PermissionDenied: Acces refuzat
DidNotGetEmail: Nu aţi primit e-mailul?
CreatePassword: Creează parolă
EmailVerification: Verificare a email-ului
Verification: Verificare
Registration: Înregistrare
ResendEmail: Retrimiteți e-mailul
LoginRequired: Trebuie să vă autentificați pentru a accesa această pagină
AnotherAccountAccessProhibited: Accesul la contul altui utilizator este interzis
OtherProfileChangeRestricted: Modificarea profilului altui utilizator este restricționată
GmailAccountNotSet: Contul Gmail nu este setat. Inițializați jetoanele.
Authentication: Autentificare
PasswordRecovery: Recuperarea parolei
ForgotPassword: Forgot password
ForgotYourPassword: Ați uitat parola?
DoNotHaveAnAccount: Nu aveți cont?
CreateAccount: Creează-ți un cont
GmailAccount: Cont Gmail
ClickToVerifyAccount: Faceți clic pe linkul din e-mail pentru a vă verifica contul
JustSentEmailTo: Tocmai am trimis un e-mail la
VerifyEmailPlease: Vă rugăm să vă verificați e-mailul
SignInViaEmail: Conectați-vă prin e-mail
Cleared: S-a șters
InvalidFormData: Date de formular nevalide
RecordDeleted: Înregistrarea a fost ștearsă
ClearSettings: Ștergeți
RecordEdited: Înregistrarea a fost editată
InvalidStoreType: Tip de stocare nevalid
StoreType: Tipul de stocare
Database: Baza de date
UserSession: Sesiunea de utilizator
GoogleSecretManager: Google Secret Manager
Initialize: Inițializează
Tokens: Jetoane
UserRegistered: Utilizatorul înregistrat
FullName: Numele complet
Save: Salvează
Cancel: Renunță
UserAccount: Cont de utilizator
Photo: Foto
Password: Parola
EmailAddress: Adresa de e-mail
Or: sau
Back: Înapoi
SignInWithGoogle: Conectați-vă cu Google
VideoConference: Conferință video
SignOut: Deconectați-vă
SignIn: Conectați-vă
SignUp: Înregistrați-vă
Login: Autentificare
MainMenu: Meniu principal
Welcome: Bine ați venit
AppDescription: Cabinet medical
AppName: MedCab

Doc001: Integrare cu API-uri externe