Cleared: S-a șters
InvalidFormData: Date de formular nevalide
RecordDeleted: Înregistrarea a fost ștearsă
ClearSettings: Ștergeți
RecordEdited: Înregistrarea a fost editată
InvalidStoreType: Tip de stocare nevalid
StoreType: Tipul de stocare
Database: Baza de date
UserSession: Sesiunea de utilizator
Initialize: Inițializează
Tokens: Jetoane
UserRegistered: Utilizatorul înregistrat
FullName: Numele complet
Save: Salvează
Cancel: Renunță
UserAccount: Cont de utilizator
Photo: Foto
Password: Parola
EmailAddress: Adresa de e-mail
Or: sau
Back: Înapoi
SignInWithGoogle: Conectați-vă cu Google
VideoConference: Conferință video
SignOut: Deconectați-vă
SignIn: Conectați-vă
SignUp: Înregistrați-vă
Login: Autentificare
MainMenu: Meniu principal
Welcome: Bine ați venit
AppDescription: Cabinet medical
AppName: MedCab