AlreadyExists: Уже существует
BasicEntities: Основные сущности
CertificateDate: Дата сертификата
Specializations: Специализации
SpecialtyTitle: Должность
BackToHomepage: Вернуться на домашнюю страницу
DemoUserAccounts: Демо-аккаунты
ThankYou: Спасибо
ConfirmEmailPlease: Пожалуйста, подтвердите свой адрес электронной почты, нажав на ссылку ниже
VerifyYourEmailAddress: Проверьте свой адрес электронной почты
AccessDeniedAdminsOnly: Доступ к этой странице имеют только администраторы. Пожалуйста, войдите под учетной записью администратора.
ClientSecret: Секрет клиента
ClientId: Идентификатор клиента
Attribution: Атрибуция
None: Ни одно
SuperuserCannotBeDeleted: Суперпользователя нельзя удалить
Administrator: Администратор
Username: Имя пользователя
Superuser: Суперпользователь
NotSpecified: Не указано
No: Нет
Yes: Да
Email: Электронная почта
Google: Google
Verified: Проверено
VerificationKey: Ключ проверки
User: Пользователь
NoUsersYet: Пользователей пока нет
Add: Добавить
Users: Пользователи
Subspecialty: Специализация
NoSubspecialtiesYet: Специализаций пока нет
Details: Подробности
Subspecialties: Специализации
Tabs: Вкладки
ConfirmPlease: Пожалуйста подтвердите
DeleteAreYouSure: Вы уверены, что хотите удалить?
ErDiagram: ER-диаграмма
Name: Имя
Code: Код
Description: Описание
NoSpecialtiesYet: Специальностей пока нет
Specialties: Специальности
Specialty: Специальность
Dele: Удалить
RecordCreated: Запись создана
Doctor: Врач
Specialization: Специализация
Mobile: Мобильный 
NoDoctorsYet: Врачей пока нет
InvalidUrlOrRemoved: Неверный URL-адрес или ресурс удален
PageNotFound: Страница не найдена
Resources: Ресурсы
SourceCode: Исходный код
Documentation: Документация
Doctors: Врачи
Data: Данные
NotIndicated: Не указано
Birthday: День рождения
Other: Другой
Male: Мужской
Female: Женский
Gender: Пол
Edit: Редактировать
PersonalInfo: Персональные данные
Account: Учетная запись
Home: Главная
HomePage: Домашняя страница
PermissionDenied: Доступ запрещен
DidNotGetEmail: Не получили письмо?
CreatePassword: Создание пароля
EmailVerification: Проверка электронной почты
Verification: Проверка
Registration: Регистрация
ResendEmail: Отправить письмо повторно
LoginRequired: Вы должны авторизоваться, чтобы получить доступ к этой странице
AnotherAccountAccessProhibited: Доступ к учетной записи другого пользователя запрещен
OtherProfileChangeRestricted: Изменение профиля другого пользователя ограничено
GmailAccountNotSet: Аккаунт Gmail не установлен. Инициализируйте токены.
Authentication: Аутентификация
PasswordRecovery: Восстановление пароля
ForgotPassword: Forgot password
ForgotYourPassword: Забыли пароль?
DoNotHaveAnAccount: У вас нет учетной записи?
CreateAccount: Зарегистрироваться
GmailAccount: Учетная запись Gmail
ClickToVerifyAccount: Нажмите ссылку в письме, чтобы подтвердить свою учетную запись
JustSentEmailTo: Мы только что отправили электронное письмо на
VerifyEmailPlease: Пожалуйста, подтвердите вашу электронную почту
SignInViaEmail: Войти по электронной почте
Cleared: Очищено
InvalidFormData: Неверные данные формы
RecordDeleted: Запись удалена
ClearSettings: Сбросить
RecordEdited: Запись отредактирована
InvalidStoreType: Неверный тип хранилища
StoreType: Тип хранилища
Database: База данных
UserSession: Пользовательская сессия
GoogleSecretManager: Google Secret Manager
Initialize: Инициализировать
Tokens: Токены
UserRegistered: Пользователь зарегистрирован
FullName: Full name
Save: Сохранить
Cancel: Отмена
UserAccount: Учетная запись пользователя
Photo: Фото
Password: Пароль
EmailAddress: Адрес электронной почты
Or: или
Back: Вернуться
SignInWithGoogle: Войти через Google
VideoConference: Видео-конференция
SignOut: Выйти
SignIn: Войти
SignUp: Зарегистрироваться
Login: Вход
MainMenu: Главное меню
Welcome: Добро пожаловать
AppDescription: Медицинский кабинет
AppName: MedCab

Doc001: Интеграция с внешними API

Doc002: Учетная запись суперпользователя определяется во время развертывания. Суперпользователь управляет другими пользователями и предоставляет или отзывает права администратора конкретным пользователям.