UserRegistered: Пользователь зарегистрирован
FullName: Full name
Save: Сохранить
Cancel: Отмена
UserAccount: Учетная запись пользователя
Photo: Фото
Password: Пароль
EmailAddress: Адрес электронной почты
Or: или
Back: Вернуться
SignInWithGoogle: Войти через Google
VideoConference: Видео-конференция
SignOut: Выйти
SignIn: Войти
SignUp: Зарегистрироваться
Login: Вход
MainMenu: Главное меню
Welcome: Добро пожаловать
AppDescription: Медицинский кабинет
AppName: MedCab